// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-jGoX1xazT6q6zvcXq_CSNfmrpGsJhBw',
    appId: '1:704094492497:web:6417e1c8c7add728dd6570',
    messagingSenderId: '704094492497',
    projectId: 'sirdad-f1fea',
    authDomain: 'sirdad-f1fea.firebaseapp.com',
    databaseURL: 'https://sirdad-f1fea-default-rtdb.firebaseio.com',
    storageBucket: 'sirdad-f1fea.appspot.com',
    measurementId: 'G-8G0QV6ZH2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6QokLgR95DW6tcWUxiLz2-47n2dfbBrc',
    appId: '1:704094492497:android:9481a347fae2be12dd6570',
    messagingSenderId: '704094492497',
    projectId: 'sirdad-f1fea',
    databaseURL: 'https://sirdad-f1fea-default-rtdb.firebaseio.com',
    storageBucket: 'sirdad-f1fea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6689qyuOBTvkqE5h_xmD_lBfWswBwwiU',
    appId: '1:704094492497:ios:59b63455c3014b83dd6570',
    messagingSenderId: '704094492497',
    projectId: 'sirdad-f1fea',
    databaseURL: 'https://sirdad-f1fea-default-rtdb.firebaseio.com',
    storageBucket: 'sirdad-f1fea.appspot.com',
    iosBundleId: 'com.example.sirdad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6689qyuOBTvkqE5h_xmD_lBfWswBwwiU',
    appId: '1:704094492497:ios:13783a9e9d55c4ecdd6570',
    messagingSenderId: '704094492497',
    projectId: 'sirdad-f1fea',
    databaseURL: 'https://sirdad-f1fea-default-rtdb.firebaseio.com',
    storageBucket: 'sirdad-f1fea.appspot.com',
    iosBundleId: 'com.example.sirdad.RunnerTests',
  );
}
