// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDykNN5VWJ07IkZNTtLyMxyRux8SaChoQw',
    appId: '1:647456780174:web:e72305e330cba1f216bedf',
    messagingSenderId: '647456780174',
    projectId: 'sirdad-db',
    authDomain: 'sirdad-db.firebaseapp.com',
    storageBucket: 'sirdad-db.appspot.com',
    measurementId: 'G-0Z2GSHYS7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPkPw-zjNSxHHMQfMVlECM_-zFVbJTJew',
    appId: '1:647456780174:android:e62a86be66678d5d16bedf',
    messagingSenderId: '647456780174',
    projectId: 'sirdad-db',
    storageBucket: 'sirdad-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDhbT6Uxq00Wx4myJ_TctmQCA-bZNsjdQ',
    appId: '1:647456780174:ios:dd1e727a566b2e9616bedf',
    messagingSenderId: '647456780174',
    projectId: 'sirdad-db',
    storageBucket: 'sirdad-db.appspot.com',
    iosBundleId: 'com.example.sirdad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDhbT6Uxq00Wx4myJ_TctmQCA-bZNsjdQ',
    appId: '1:647456780174:ios:fbc7aec445f77cd416bedf',
    messagingSenderId: '647456780174',
    projectId: 'sirdad-db',
    storageBucket: 'sirdad-db.appspot.com',
    iosBundleId: 'com.example.sirdad.RunnerTests',
  );
}
