// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAj4AhsWkZPcAfCFFLvvxIIbvxNz0h4lw',
    appId: '1:623455353282:web:97b100bd1e1e6e7c937e5b',
    messagingSenderId: '623455353282',
    projectId: 'sirdad-sql',
    authDomain: 'sirdad-sql.firebaseapp.com',
    databaseURL: 'https://sirdad-sql-default-rtdb.firebaseio.com',
    storageBucket: 'sirdad-sql.appspot.com',
    measurementId: 'G-KW73GZ2TBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXi_QKuv4UYfMAa9ssPRTDhAE3St_FZiQ',
    appId: '1:623455353282:android:be393eec6f36655d937e5b',
    messagingSenderId: '623455353282',
    projectId: 'sirdad-sql',
    databaseURL: 'https://sirdad-sql-default-rtdb.firebaseio.com',
    storageBucket: 'sirdad-sql.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzFev6Tkkf_cdE9st00DQ5zJJyrQqAMAM',
    appId: '1:623455353282:ios:c2d31f053ea0aa93937e5b',
    messagingSenderId: '623455353282',
    projectId: 'sirdad-sql',
    databaseURL: 'https://sirdad-sql-default-rtdb.firebaseio.com',
    storageBucket: 'sirdad-sql.appspot.com',
    iosBundleId: 'com.example.sirdad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzFev6Tkkf_cdE9st00DQ5zJJyrQqAMAM',
    appId: '1:623455353282:ios:27cd761bac9d5f28937e5b',
    messagingSenderId: '623455353282',
    projectId: 'sirdad-sql',
    databaseURL: 'https://sirdad-sql-default-rtdb.firebaseio.com',
    storageBucket: 'sirdad-sql.appspot.com',
    iosBundleId: 'com.example.sirdad.RunnerTests',
  );
}
